config/routes.rb
Rails.application.routes.draw do

  match 'login', to: "user_sessions#new", via: :get
  match 'logout', to: "user_sessions#destroy", via: :get
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots

  resources :user_sessions, only: :create
  resources :documents, only: :show
  resources :messages, only: :create

  scope '(:locale)' do
    root 'articles#index'
    resources :tags, param: :slug, only: [] do
      resources :articles, path: 'blog', only: :index
    end
    resources :articles, path: 'blog', param: :slug, only: [:index, :show]
  end

  namespace :admin do
    resources :tags, except: :new
    resources :article_tags, only: :destroy
    resources :articles do
      resources :tags, only: :index
      resources :article_tags, only: :create
    end
 end

 get 'admin/articles/:article_id/avatars/edit', 
  to: 'admin/article_avatars#edit', 
  as: 'edit_admin_article_avatar'
  match '/:document', to: 'documents#show', via: :get
  match '/:layout/:document', to: 'documents#show', via: :get, 
            defaults: { layout: :plain }

end

app/models/article.rb
# Model for articles
class Article < ActiveRecord::Base
  mount_uploader :image, ArticleImageUploader

  has_many :article_tag_positions, -> { order('article_tag_positions.position ASC') },
           dependent: :delete_all
  has_many :tags, through: :article_tag_positions
  has_many :translated_articles, dependent: :delete_all
  has_many :article_relations, dependent: :delete_all
  has_many :related_articles,  -> { select('articles.*, article_relations.kind') },
           through: :article_relations

  has_one :translated_article, -> { merge(TranslatedArticle.localized(I18n.locale)) }
  has_one :article_relation
  has_one :previous_article_relation, -> { previous },
          class_name: ArticleRelation
  has_one :previous_article, through: :previous_article_relation,
                             source: :related_article
  has_one :next_article_relation, -> { merge(ArticleRelation.next) },
          class_name: ArticleRelation
  has_one :next_article, through: :next_article_relation,
                         source: :related_article

  before_validation :set_slug
  validates :slug, uniqueness: true, allow_nil: true
  validates :slug, presence: true, if: :released?

  scope :published, -> { where('published_at < ?', Time.current) }
  scope :published_before, ->(time) { published.where('published_at < ?', time) }
  scope :published_after, ->(time) { published.where('published_at > ?', time) }
  scope :by_publishing, ->(order = :desc) { order(published_at: order) }
  scope :by_creation, -> { order("#{table_name}.created_at ASC") }
  scope :search, ->(term) {
    return if term.blank?
    joins(:translated_article)
      .merge(TranslatedArticle.search(term))
  }
  scope :tagged, ->(tag_slug) {
    joins(:tags).merge(Tag.slugged(tag_slug)) if tag_slug.present?
  }

  delegate :title, :text, :summary, to: :translated_article

  def released?
    published_at.present?
  end

  private

  def set_slug
    self.slug = translation.title.parameterize
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  # Controller for adminstrating articles
  class ArticlesController < ApplicationController
    rescue_from ActiveRecord::RecordInvalid, with: :render_validation

    def index
      @articles = Article.preload(:tags, :translated_article)
                         .by_publishing
                         .by_creation
    end

    def show
      @article = Article.find params[:id]
      @article.published_at ||= Time.current
      render template: 'articles/show'
    end

    def new
      @article = Article.new
      render action: :edit
    end

    def create
      @article = ArticlePersistence.new Article.new
      @article.attributes = article_params
      @article.save!
      flash[:notice] = success_note(@article)
      redirect_to [:edit, :admin, @article]
    end

    def edit
      @article = Article.find params[:id]
    end

    def update
      article = ArticlePersistence.find(params[:id])
      article.attributes = article_params
      article.save!

      flash[:notice] = success_note(article)
      respond_to do |format|
        format.js { render template: 'shared/message' }
        format.html { redirect_to [:edit, :admin, article] }
      end
    end

    def destroy
      @article = Article.find params[:id]
      ArticlePersistence.destroy(@article)
    end

    private

    def success_note(article)
      I18n.t('admin.articles.saved',
             title: article.translated_articles.localized(locale).first.title)
    end

    def render_validation(record_invalid_exception)
      @errors = record_invalid_exception.record.errors
      render template: 'shared/validate'
    end

    def article_params
      params.require(:article)
            .permit(:published_at, :image,
                    tag_ids: [],
                    translated_articles: {
                      en: %i(title text summary),
                      de: %i(title text summary)
                    })
            .transform_values { |value| value if value.present? }
    end
  end
end

app/controllers/articles_controller.rb
# Controller for articles
class ArticlesController < ApplicationController
=begin
  def index
    @articles = Article.published
                       .tagged(params[:tag_slug])
                       .search(params[:search])
                       .preload(:tags, :translated_article)
                       .by_publishing
  end
=end
  def index
    @articles = TranslatedArticle.by_publishing
                       .tagged(params[:tag_slug])
                       .search(params[:search])
                       .preload(:tags)
  end
=begin
  def show
    @article = Article.preload(:tags)
                      .find_by_slug(params[:slug])
    alternate_to alternate_url(@article)
  end
=end
  def show
    @article = TranslatedArticle.preload(:tags)
                                .find(params[:slug])
  end

  private

  def alternate_url(article)
    url_for params.merge(locale: @locale.secondary, slug: article.slug)
  end
end

app/views/admin/articles/_article.html.haml
%li.alternated.list-group-item.clearfix{ id: dom_id(article) }
  .row
    .col-md-8
      %h1.h3.lobster
        = article.title
      = present(article, ArticlePresenter).tags_with_icon
    .col-md-2
      = decorate(article).published_on
    .col-md-2.text-right
      = link_to('', article, rel: 'preview', 
          class: 'btn btn-default glyphicon glyphicon-eye-open',
          target: '_blank') if article.released?
      = link_to '', [:edit, :admin, article], 
          class: 'btn btn-default glyphicon glyphicon-pencil'
      = link_to '', [:admin, article], remote: true, method: :delete, 
          class: 'btn btn-default glyphicon glyphicon-trash'

app/views/admin/articles/_form.html.haml
.messages.alert= flash[:notice]
= form_for [:admin, @article], html: { id: nil, class: 'admin article' },
    remote: !@article.new_record? do |f|
  - present(@article) do |article_presenter|
    .row
      .col-xs-12.col-md-3
        = article_presenter.link_to_avatar

      .col-xs-12.col-md-5
        .row
          .col-xs-12.col-md-7.btn-group.round
            = f.submit class: 'btn btn-default'
            = link_to t('.preview'), [:admin, @article], 
                class: 'btn btn-default' unless @article.new_record?
            = link_to t('.back'), admin_articles_path, class: 'btn btn-default'
          .col-xs-12.col-md-5
            .form-group.input-group
              %i.glyphicon.glyphicon-search.pre.form-control-mark
              = text_field_tag "tag_names", nil, autocomplete: 'off', 
                  id: nil, class: 'form-control tag search', placeholder: 'Tags',
                  data: { search: admin_tags_path }
              %span.input-group-addon.pointer
                = link_to '', admin_tags_path, remote: true,
                    class: 'glyphicon glyphicon-list-alt'
        .row
          .col-xs-12.tags
            = hidden_field_tag 'article[tag_ids][]', nil, id: nil
            = render partial: 'tag', collection: @article.tags
   
      .col-xs-12.col-md-4
        .col-xs-12.col-md-6.form-group.input-group.pull-right
          .row.text-right
            = f.label :published_at
          .row
            .input-group.text-right
              = f.datetime_local_field :published_at, class: 'form-control'
              %span.input-group-addon.pointer
                %span.glyphicon.glyphicon-calendar{ "aria-hidden" => true }

    .row
      = render partial: 'translated_article_form',
          collection: article_presenter.translated_articles_by_locale,
          as: :translated_article

app/views/admin/articles/_tag.html.haml
= check_box_tag 'article[tag_ids][]', tag.id, :checked, class: 'hidden',
    id: "tag_#{tag.id}"
= label_tag "tag_#{tag.id}", tag.name

app/views/admin/articles/_translated_article_form.html.haml
.col-sm-6.col-xs-12
  .form-group
    = label "translated_article_#{translated_article.locale}_title", 
        t(".#{translated_article.locale}")
    = text_field_tag "article[translated_articles][#{translated_article.locale}]title", 
        translated_article.title, class: 'form-control', 
        id: "translated_article_#{translated_article.locale}_title",
        placeholder: Article.human_attribute_name('title')
  .form-group
    = text_area_tag "article[translated_articles][#{translated_article.locale}]summary", 
        translated_article.summary,
        rows: 3, class: 'form-control',
        placeholder: Article.human_attribute_name('summary')
  .form-group
    = text_area_tag "article[translated_articles][#{translated_article.locale}]text", 
        translated_article.text,
        rows: 40, class: 'form-control',
        placeholder: Article.human_attribute_name('content')

app/views/admin/articles/create.js.erb
window.location = '<%= j(edit_admin_article_path @article) %>'

app/views/admin/articles/destroy.js.erb
$('#<%= dom_id @article %>').remove()

app/views/admin/articles/edit.html.haml
= render 'form'

app/views/admin/articles/index.html.haml
.margin-bottom-md
#user_nav.admin
  - if current_user
    .row.margin-bottom-md
      .col-md-2
        = link_to t('.new'), new_admin_article_path, class: 'btn btn-default' 

      .col-md-8
      .col-md-1
        = link_to "Logout", logout_path, class: 'btn btn-default'
    %ul.list-group.articles
      = render @articles

  - else
    .pull-right= link_to "Login", login_path, class: 'btn btn-default'

app/views/admin/articles/new.html.haml
= render 'form'