config/routes.rb
Rails.application.routes.draw do

  match 'login', to: "user_sessions#new", via: :get
  match 'logout', to: "user_sessions#destroy", via: :get
  get "sitemap.xml" => "home#sitemap", format: :xml, as: :sitemap
  get "robots.txt" => "home#robots", format: :text, as: :robots

  resources :user_sessions, only: :create
  resources :documents, only: :show
  resources :messages, only: :create

  scope '(:locale)' do
    root 'articles#index'
    resources :tags, param: :slug, only: [] do
      resources :articles, path: 'blog', only: :index
    end
    resources :articles, path: 'blog', param: :slug, only: [:index, :show]
  end

  namespace :admin do
    resources :tags, except: :new
    resources :article_tags, only: :destroy
    resources :articles do
      resources :tags, only: :index
      resources :article_tags, only: :create
    end
 end

 get 'admin/articles/:article_id/avatars/edit', 
  to: 'admin/article_avatars#edit', 
  as: 'edit_admin_article_avatar'
  match '/:document', to: 'documents#show', via: :get
  match '/:layout/:document', to: 'documents#show', via: :get, 
            defaults: { layout: :plain }

end

app/models/translated_article.rb
# frozen_string_literal: true

# Model for tranlsated articles. That are the translationable elements of an article.
class TranslatedArticle < ActiveRecord::Base
  enum locale: { en: 1, de: 2 }

  belongs_to :article
  has_many :article_relations, through: :article
  has_many :article_tag_positions, through: :article
  has_many :tags, through: :article_tag_positions

  validates :title, uniqueness: { scope: :locale },
                    length: { in: 3..200 },
                    allow_blank: true
  validates :text, presence: true,
                   if: -> { released? && title.present? }

  scope :localized, ->(locale) {
    where(table_name => { locale: locales[locale.to_s] })
  }
  scope :by_publishing, -> do
    eager_load(:article)
      .merge(Article.published)
      .merge(Article.by_publishing)
  end
  scope :search, ->(term) {
    term = term.to_s.strip
    return if term.empty?
    where('title LIKE ?', "%#{term}%")
  }
  scope :tagged, ->(tag_slug) do
    return if tag_slug.blank?
    joins(:tags).merge(Tag.slugged(tag_slug))
  end

  def to_param
    "#{id}-#{slug}"
  end

  delegate :released?, :published_at, :image, to: :article
end

app/views/admin/translated_articles/_article.html.haml
%li.alternated.list-group-item.clearfix{ id: dom_id(translated_article) }
  .row
    .col-md-8
      %h1.h3.lobster
        = translated_article.title
      = present(translated_article, ArticlePresenter).tags_with_icon
    .col-md-2
      = l translated_aarticle.published_at.to_date, format: :short
    .col-md-2.text-right
      = link_to('', translated_article_path(translated_article.slug), 
          rel: 'preview', class: 'btn btn-default glyphicon glyphicon-eye-open',
          target: '_blank') if translated_article.published?
      = link_to '', edit_admin_translated_article_path(translated_article), 
          class: 'btn btn-default glyphicon glyphicon-pencil'
      = link_to '', admin_translated_article_path(translated_article), 
          remote: true, method: :delete, 
          class: 'btn btn-default glyphicon glyphicon-trash'

app/views/admin/translated_articles/_translated_article.html.haml
%li.alternated.list-group-item.clearfix{ id: dom_id(translated_article) }
  .row
    .col-md-8
      %h1.h3.lobster
        = translated_article.title
      = present(translated_article, ArticlePresenter).tags_with_icon
    .col-md-2
      = l translated_article.published_at.to_date, format: :short
    .col-md-2.text-right
      = link_to('', article_path(translated_article.slug), 
          rel: 'preview', class: 'btn btn-default glyphicon glyphicon-eye-open',
          target: '_blank') if translated_article.released?
      = link_to '', edit_admin_article_path(translated_article.article), 
          class: 'btn btn-default glyphicon glyphicon-pencil'
      = link_to '', admin_article_path(translated_article.article), 
          remote: true, method: :delete, 
          class: 'btn btn-default glyphicon glyphicon-trash'